### ISSUE TITLE
me.zeroeightsix.kami.event.events.PacketEvent is nowhere to be found

### ISSUE THREAD

**Issue by Smargi1** [ZeroMemes/Alpine#2]
Hey so I wanted to mess around in the code for a bit but I saw that event.events.PacketEvent is nowhere to be found in it

**Comment by x4e** [comment]
Is this a joke?

**Comment by 5HT2** [comment]
Do you know what Alpine is??

**Comment by RealIndrit** [comment]
Nice troll dude

**Comment by 5HT2** [comment]
Holy shit you're the same person that made this issue lmao https://github.com/BleachDrinker420/bleachhack-1.14/issues/56

**Comment by kylerittenhause** [comment]
ja
